/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {

    public static void main(String[] args) {

        // Create SnS Topic
        String topicName = "MySampleTopic";
        String topicArn = SnSAdapter.createSnSTopic(topicName);

        // Create SqS Queue
        String queueName = "MySampleQueue";
        String queueUrl = SqSAdapter.createQueue(queueName);

        // Subscribe the Queue to the Topic
        SqSAdapter.subscribeQueue(topicArn, queueUrl);

        // Publish a sample message to the Topic, and it will be send to the Queue
        String message = "Hello Mr. Queue!";
        SnSAdapter.publishMessage(topicArn, message);
    }
}
