/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
    public String getGreeting() {
        return "Hello John.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
        String topicArn = SnSAdapter.createSnSTopic();
        String queueUrl = SqSAdapter.createQueue();
        SqSAdapter.subscribeQueue(topicArn, queueUrl);
        SnSAdapter.publishMessage(topicArn);
    }
}
